name: IncludeJS

on:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake --version
      - uses: ilammy/msvc-dev-cmd@v1
      - run: nmake webkit
