name: website
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DINCLUDEJS_ENGINE:BOOL=OFF
          -DINCLUDEJS_TESTS:BOOL=OFF
          -DINCLUDEJS_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
