name: website
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: website-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DINCLUDEJS_ENGINE:BOOL=OFF
          -DINCLUDEJS_TESTS:BOOL=OFF
          -DINCLUDEJS_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/website
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
